Repository unsw-cse-comp99-3900/capstone-project-2025-t1-25t1-9900-w16a-brioche, pull requests merged in 2025-03, with the labels that each got.

#1 chore: set up react compiler
  frontend/eslint.config.js
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/vite.config.ts
Labels: chore

#3 Doc: add readme
  README.md
Labels: documentation

#4 Doc: update readme for frontend dev
  README.md
Labels: documentation

#5 Chore: GitHub action ci setup
  .github/workflows/frontend-lint.yml
  frontend/.prettierrc
  frontend/LINT-README.md
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: chore

#7 Refactor: Standardize code formatting
  frontend/LINT-README.md
  frontend/README.md
  frontend/components.json
  frontend/eslint.config.js
  frontend/postcss.config.js
  frontend/src/App.tsx
  frontend/src/components/ui/button.tsx
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/tailwind.config.js
  frontend/vite.config.ts
Labels: enhancement

#8 Doc: Add documentation for frontend project structure
  frontend/.prettierrc
  frontend/src/components/components.md
  frontend/src/components/layout/layout.md
  frontend/src/constants/constants.md
  frontend/src/containers/containers.md
  frontend/src/context/context.md
  frontend/src/hooks/hooks.md
  frontend/src/pages/pages.md
  frontend/src/routes/routes.md
  frontend/src/styles/styles.md
  frontend/src/types/types.md
  frontend/src/utils/utils.md
Labels: documentation

#17 Chore: update GitHub action ci setting
  .github/workflows/frontend-lint.yml
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/App.tsx
  frontend/src/components/common/GlowEffect.tsx
  frontend/src/components/common/GridPatternOverlay.tsx
  frontend/src/components/landing/BrowserFrame.tsx
  frontend/src/components/landing/FeatureBadge.tsx
  frontend/src/components/landing/FeatureItem.tsx
  frontend/src/components/landing/FeatureList.tsx
  frontend/src/components/landing/HeroBackground.tsx
  frontend/src/components/landing/HeroButton.tsx
  frontend/src/components/landing/HeroButtons.tsx
  frontend/src/components/landing/HeroContent.tsx
  frontend/src/components/landing/HeroHeading.tsx
  frontend/src/components/landing/HeroShowcase.tsx
  frontend/src/components/landing/ProcessFlow.tsx
  frontend/src/components/landing/ShowcaseBadge.tsx
  frontend/src/constants/Landing/landingHero.ts
  frontend/src/constants/index.ts
  frontend/src/containers/Landing/HeroContainer.tsx
  frontend/src/pages/LandingPage.tsx
Labels: chore

#14 Chore: backend setup .net core api
  .gitignore
  backend/InvoiceBackend/Controllers/InvoicesController.cs
  backend/InvoiceBackend/InvoiceBackend.csproj
  backend/InvoiceBackend/InvoiceBackend.csproj.user
  backend/InvoiceBackend/InvoiceBackend.http
  backend/InvoiceBackend/InvoiceBackend.sln
  backend/InvoiceBackend/Program.cs
  backend/InvoiceBackend/Properties/launchSettings.json
  backend/InvoiceBackend/appsettings.Development.json
  backend/InvoiceBackend/appsettings.json
Labels: chore

#18 Chore: react query axio setup
  backend/InvoiceBackend/Controllers/InvoicesController.cs
  backend/InvoiceBackend/Program.cs
  frontend/netlify.toml
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/App.tsx
  frontend/src/components/example/InvoiceList.tsx
  frontend/src/constants/config.ts
  frontend/src/constants/index.ts
  frontend/src/hooks/useInvoices.ts
  frontend/src/lib/axios.ts
  frontend/src/pages/ApiTestPage.tsx
  frontend/src/routes/index.tsx
  frontend/src/types/invoice.ts
Labels: chore

#19 feat: Integrate Clerk authentication into frontend
  .gitignore
  frontend/.env.example
  frontend/.gitignore
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/auth/AuthButtonGroup.tsx
  frontend/src/components/auth/ProtectedRoute.tsx
  frontend/src/components/auth/SignInButton.tsx
  frontend/src/components/auth/SignUpButton.tsx
  frontend/src/components/layout/LandingLayout.tsx
  frontend/src/lib/api.ts
  frontend/src/lib/axios.ts
  frontend/src/main.tsx
  frontend/src/routes/index.tsx
Labels: chore

#20 Feat: Added LandingPage Header
  frontend/src/components/auth/AuthButtonGroup.tsx
  frontend/src/components/auth/SignInButton.tsx
  frontend/src/components/common/Footer.tsx
  frontend/src/components/common/LandingHeader.tsx
  frontend/src/components/common/Logo.tsx
  frontend/src/components/layout/LandingLayout.tsx
  frontend/src/components/ui/button.tsx
  frontend/src/index.css
  frontend/src/pages/LandingPage.tsx
Labels: enhancement

#23 add some test api
  .gitignore
  backend/InvoiceBackend/Controllers/CustomersController.cs
  backend/InvoiceBackend/Controllers/InvoicesController.cs
  backend/InvoiceBackend/Controllers/ItemsController.cs
  backend/InvoiceBackend/Program.cs
  backend/InvoiceBackend/Services/ReckonApiService/IReckonApiService.cs
  backend/InvoiceBackend/Services/ReckonApiService/ReckonApiService.cs
  backend/InvoiceBackend/appsettings.json
  frontend/src/hooks/useInvoices.ts
Labels: chore

#24 Refactor: Update 404 page routing in index.tsx
  frontend/src/containers/NotFoundContainer.tsx
  frontend/src/routes/index.tsx
Labels: bug

#25 Feat: add route protection
  frontend/src/components/landing/HeroButtons.tsx
  frontend/src/routes/index.tsx
Labels: enhancement

#22 Feat add landing keyfeature section
  frontend/src/components/landing/FeaturesBackground.tsx
  frontend/src/components/landing/FeaturesContent.tsx
  frontend/src/components/landing/IconWrapper.tsx
  frontend/src/components/landing/KeyFeatureCard.tsx
  frontend/src/components/landing/KeyFeatureHeader.tsx
  frontend/src/components/landing/KeyFeatureHighlight.tsx
  frontend/src/components/landing/KeyFeaturelist.tsx
  frontend/src/components/landing/KeyFeaturesShowcase.tsx
  frontend/src/constants/Landing/landingFeature.ts
  frontend/src/containers/Landing/FeatureSectionContainer.tsx
  frontend/src/pages/LandingPage.tsx
Labels: enhancement

#28 Feat dashboard header
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/common/DashboardHeader.tsx
  frontend/src/components/common/LandingHeader.tsx
  frontend/src/components/common/LogoTextGroup.tsx
  frontend/src/components/layout/DashboardLayout.tsx
  frontend/src/components/ui/collapsible.tsx
  frontend/src/components/ui/navigation-menu.tsx
  frontend/src/components/ui/popover.tsx
  frontend/src/components/ui/sheet.tsx
Labels: enhancement

#29 Feat: add customs page
  backend/InvoiceBackend/Controllers/CustomersController.cs
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/common/DashboardHeader.tsx
  frontend/src/components/ui/badge.tsx
  frontend/src/components/ui/checkbox.tsx
  frontend/src/components/ui/data-table.tsx
  frontend/src/components/ui/dropdown-menu.tsx
  frontend/src/components/ui/input.tsx
  frontend/src/components/ui/label.tsx
  frontend/src/components/ui/pagination.tsx
  frontend/src/components/ui/select.tsx
  frontend/src/components/ui/table.tsx
  frontend/src/constants/config.ts
  frontend/src/containers/Customers/CustomerContentHeader.tsx
  frontend/src/containers/Customers/CustomerTableContainer.tsx
  frontend/src/containers/Customers/index.ts
  frontend/src/containers/Customers/useCustomerActions.ts
  frontend/src/hooks/useCustomers.ts
  frontend/src/lib/axios.ts
  frontend/src/pages/CustomersPage.tsx
  frontend/src/routes/index.tsx
  frontend/src/types/customer.ts
  frontend/vite.config.ts
Labels: enhancement

#30 Feat: Implement loading page and container
  frontend/src/components/auth/ProtectedRoute.tsx
  frontend/src/containers/LoadingContainer.tsx
  frontend/src/pages/LoadingPage.tsx
  frontend/src/routes/index.tsx
Labels: enhancement

#34 Feat: add create custom page
  backend/InvoiceBackend/Controllers/CustomersController.cs
  backend/InvoiceBackend/appsettings.json
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/App.tsx
  frontend/src/components/common/FormField.tsx
  frontend/src/components/common/PageHeader.tsx
  frontend/src/components/common/SectionHeader.tsx
  frontend/src/components/common/index.ts
  frontend/src/components/ui/3d-card.tsx
  frontend/src/components/ui/background-beams-with-collision.tsx
  frontend/src/components/ui/background-gradient.tsx
  frontend/src/components/ui/badge.tsx
  frontend/src/components/ui/form.tsx
  frontend/src/components/ui/navigation-menu.tsx
  frontend/src/components/ui/switch.tsx
  frontend/src/components/ui/text-generate-effect.tsx
  frontend/src/components/ui/textarea.tsx
  frontend/src/containers/Customers/CreateCustomerContainer.tsx
  frontend/src/containers/Customers/CustomerContentHeader.tsx
  frontend/src/containers/Customers/index.ts
  frontend/src/containers/Customers/useCustomerActions.ts
  frontend/src/hooks/useCreateCustomer.ts
  frontend/src/hooks/useCustomers.ts
  frontend/src/index.css
  frontend/src/pages/CreateCustomerPage.tsx
  frontend/src/pages/CustomersPage.tsx
  frontend/src/routes/index.tsx
  frontend/src/types/customer.ts
Labels: documentation

#35 Feat: add cuntom delete
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/common/FormField.tsx
  frontend/src/components/ui/alert-dialog.tsx
  frontend/src/containers/Customers/CustomerTableContainer.tsx
  frontend/src/containers/Customers/DeleteCustomerDialog.tsx
  frontend/src/hooks/useDeleteCustomer.ts
  frontend/src/pages/CustomersPage.tsx
Labels: enhancement

#37 Doc: update readme
  README.md
Labels: documentation

#41 chore: Updateappsettings.json for ReckonAPI
  backend/InvoiceBackend/appsettings.json
Labels: chore

#40 add benefits section landingpage
  frontend/src/components/landing/BenefitsPage/BenefitSlideButton.tsx
  frontend/src/components/landing/BenefitsPage/BenefitsBackground.tsx
  frontend/src/components/landing/BenefitsPage/BenefitsCTA.tsx
  frontend/src/components/landing/BenefitsPage/BenefitsCard.tsx
  frontend/src/components/landing/BenefitsPage/BenefitsHeader.tsx
  frontend/src/components/landing/BenefitsPage/CTABackground.tsx
  frontend/src/components/landing/BenefitsPage/CTAButton.tsx
  frontend/src/components/landing/BenefitsPage/CTAContent.tsx
  frontend/src/constants/Landing/landingbenefits.tsx
  frontend/src/containers/Landing/BenefitsContainer.tsx
  frontend/src/containers/Landing/CTAContainer.tsx
  frontend/src/pages/LandingPage.tsx
Labels: enhancement

#45 feat: Enhance landing page navigation and styling
  frontend/src/components/common/Footer.tsx
  frontend/src/components/common/LandingHeader.tsx
  frontend/src/containers/Landing/FeatureSectionContainer.tsx
  frontend/src/containers/Landing/ProcessContainer.tsx
  frontend/src/index.css
Labels: enhancement

#44 feat: Update country code placeholder from "+1" to "+61"
  frontend/src/containers/Customers/CreateCustomerContainer.tsx
  frontend/src/containers/Customers/EditCustomerContainer.tsx
Labels: enhancement

#46 chore：Update AccessToken in appsettings.json for ReckonAPI with new token
  backend/InvoiceBackend/appsettings.json
Labels: chore

#47 feat: update landing background
  frontend/src/components/landing/BenefitsPage/BenefitsBackground.tsx
  frontend/src/components/landing/ProcessBackground.tsx
Labels: enhancement

#53 Fix: product list sort search
  backend/InvoiceBackend/appsettings.json
  frontend/src/containers/Products/ProductTableContainer.tsx
  frontend/src/types/product.ts
Labels: bug

#54 Fix：Invoice table search sort
  frontend/src/containers/Invoices/InvoiceTableContainer.tsx
  frontend/src/types/invoice.ts
Labels: bug

#57 Feat: Add ScrollToTopButton component
  frontend/src/containers/Landing/FAQContainer.tsx
  frontend/src/containers/Landing/ScrollToTopButton.tsx
  frontend/src/pages/LandingPage.tsx
Labels: enhancement

#58 Style: dashboad mobile tabs and badge color
  backend/InvoiceBackend/appsettings.json
  frontend/src/containers/Dashboard/DashboardStatsContainer.tsx
  frontend/src/containers/Invoices/InvoiceTableContainer.tsx
Labels: enhancement

#61 fix: due date handling
  backend/InvoiceBackend/appsettings.json
  frontend/.gitignore
  frontend/src/containers/Invoices/CreateInvoiceContainer.tsx
  frontend/src/hooks/payment/useDueDate.ts
  frontend/src/hooks/payment/usePaymentTerms.ts
  frontend/src/types/payment.ts
Labels: bug

#60 Create invoice alfalfa
  backend/InvoiceBackend/appsettings.json
  frontend/.env.example
  frontend/.gitignore
  frontend/src/containers/Invoices/CreateInvoiceContainer.tsx
  frontend/src/hooks/payment/useDueDate.ts
  frontend/src/hooks/payment/usePaymentTerms.ts
  frontend/src/types/invoice.ts
  frontend/src/types/payment.ts
Labels: enhancement

#66 Feat: use auth axios
  backend/InvoiceBackend/appsettings.json
  frontend/src/contexts/context.md
  frontend/src/hooks/customer/useCreateCustomer.ts
  frontend/src/hooks/customer/useCustomer.ts
  frontend/src/hooks/customer/useCustomers.ts
  frontend/src/hooks/customer/useDeleteCustomer.ts
  frontend/src/hooks/customer/useEditCustomer.ts
  frontend/src/hooks/invoice/useCreateInvoice.ts
  frontend/src/hooks/invoice/useDeleteInvoice.ts
  frontend/src/hooks/invoice/useInvoices.ts
  frontend/src/hooks/payment/useDueDate.ts
  frontend/src/hooks/payment/usePaymentTerms.ts
  frontend/src/hooks/product/useCreateProduct.ts
  frontend/src/hooks/product/useDeleteProduct.ts
  frontend/src/hooks/product/useEditProduct.ts
  frontend/src/hooks/product/useProduct.ts
  frontend/src/hooks/product/useProducts.ts
  frontend/src/hooks/useDeleteCustomer.ts
  frontend/src/lib/api.ts
  frontend/src/lib/axios.ts
Labels: enhancement

#67 chore: Update AccessToken in appsettings.json
  backend/InvoiceBackend/appsettings.json
Labels: chore

#65 add ClerkAuthService backend
  backend/InvoiceBackend/Controllers/UserDataController.cs
  backend/InvoiceBackend/InvoiceBackend.csproj
  backend/InvoiceBackend/InvoiceBackend.csproj.user
  backend/InvoiceBackend/Program.cs
  backend/InvoiceBackend/Services/ClerkAuthService/ClerkAuthService.cs
  backend/InvoiceBackend/Services/ClerkAuthService/IClerkAuthService.cs
  backend/InvoiceBackend/appsettings.json
Labels: enhancement, chore

#68 fix: Update tax calculation logic in CreateInvoiceContainer
  frontend/src/containers/Invoices/CreateInvoiceContainer.tsx
Labels: bug

#71 backend get accesstoken and refreshtoken demo
  README.md
  backend/InvoiceBackend/Controllers/ReckonAuthController.cs
  backend/InvoiceBackend/DataAccess/AppDbContext.cs
  backend/InvoiceBackend/DataAccess/ReckonTokenRepository/IReckonTokenRepository.cs
  backend/InvoiceBackend/DataAccess/ReckonTokenRepository/ReckonTokenRepository.cs
  backend/InvoiceBackend/Domain/Entities/ReckonToken.cs
  backend/InvoiceBackend/InvoiceBackend.csproj
  backend/InvoiceBackend/Migrations/20250329071605_InitialCreate.Designer.cs
  backend/InvoiceBackend/Migrations/20250329071605_InitialCreate.cs
  backend/InvoiceBackend/Migrations/AppDbContextModelSnapshot.cs
  backend/InvoiceBackend/Program.cs
  backend/InvoiceBackend/Services/ReckonTokenService/IReckonTokenService.cs
  backend/InvoiceBackend/Services/ReckonTokenService/ReckonTokenService.cs
  backend/InvoiceBackend/appsettings.json
Labels: enhancement

#73 fix edit tax bug and discount bug
  backend/InvoiceBackend/appsettings.json
  frontend/src/containers/Invoices/EditInvoiceContainer.tsx
  frontend/src/types/invoice.ts
Labels: bug

#72 Feat add close state faq
  frontend/src/components/landing/FAQ_Page/FAQItem.tsx
Labels: enhancement

#74 fix edit invoice display bug
  backend/InvoiceBackend/appsettings.json
  frontend/src/containers/Invoices/EditInvoiceContainer.tsx
Labels: bug

#76 Doc: add doc to auth and common folder
  frontend/src/components/auth/AuthButtonGroup.tsx
  frontend/src/components/auth/ProtectedRoute.tsx
  frontend/src/components/auth/SignInButton.tsx
  frontend/src/components/auth/SignUpButton.tsx
  frontend/src/components/common/AuthFooter.tsx
  frontend/src/components/common/DashboardHeader.tsx
  frontend/src/components/common/Footer.tsx
  frontend/src/components/common/FormField.tsx
  frontend/src/components/common/GlowEffect.tsx
  frontend/src/components/common/GlowHoverEffect.tsx
  frontend/src/components/common/GradientAccentLine.tsx
  frontend/src/components/common/GridPatternOverlay.tsx
  frontend/src/components/common/LandingHeader.tsx
  frontend/src/components/common/Logo.tsx
  frontend/src/components/common/LogoTextGroup.tsx
  frontend/src/components/common/PageHeader.tsx
  frontend/src/components/common/SectionHeader.tsx
Labels: documentation
