Repository unsw-cse-comp99-3900/capstone-project-2025-t1-25t1-9900-w16a-brioche, pull requests merged in 2025-04, with the labels that each got.

#80 complete send invoive function
  backend/InvoiceBackend/appsettings.json
  frontend/src/components/invoice/SendInvoiceModal.tsx
  frontend/src/containers/Invoices/EditInvoiceContainer.tsx
  frontend/src/hooks/invoice/useSendInvoice.ts
Labels: enhancement

#79 feat: view invoice page demo & download function
  backend/InvoiceBackend/appsettings.json
  frontend/src/containers/Invoices/ViewInvoicContainer.tsx
  frontend/src/hooks/invoice/useDownloadInvoice.ts
  frontend/src/hooks/payment/useDueDate.ts
  frontend/src/hooks/payment/usePaymentTerms.ts
  frontend/src/pages/invoices/ViewInvoicePage.tsx
  frontend/src/routes/index.tsx
Labels: enhancement

#64 customer_book_page
  frontend/src/containers/Customers/CustomerBookContainer.tsx
  frontend/src/hooks/customer/useBookCustomer.ts
  frontend/src/pages/CustomerBookPage.tsx
  frontend/src/routes/index.tsx
  frontend/src/types/customer.ts
Labels: enhancement

#83 Feat:add create invoice from pdf
  frontend/.env.example
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/ui/file-upload-light.tsx
  frontend/src/containers/Dashboard/DashboardHeaderContainer.tsx
  frontend/src/containers/Invoice/InvoiceDetailContainer.tsx
  frontend/src/containers/Invoice/InvoiceFormContainer.tsx
  frontend/src/containers/Invoice/InvoiceUploadContainer.tsx
  frontend/src/containers/Invoice/ValidationResultsContainer.tsx
  frontend/src/containers/Invoices/CreateInvoiceContainer.tsx
  frontend/src/containers/Invoices/InvoiceContentHeader.tsx
  frontend/src/containers/Invoices/InvoicePdfUploadContainer.tsx
  frontend/src/hooks/invoice/useProcessInvoicePdf.ts
  frontend/src/pages/InvoiceCsvUploadPage.tsx
  frontend/src/pages/InvoiceDetailPage.tsx
  frontend/src/pages/InvoiceFormPage.tsx
  frontend/src/pages/InvoicePdfUploadPage.tsx
  frontend/src/pages/ValidationResultsPage.tsx
  frontend/src/routes/index.tsx
  frontend/vite.config.ts
Labels: enhancement

#84 fix: update product selection value in CreateInvoiceContainer to use …
  frontend/src/containers/Invoices/CreateInvoiceContainer.tsx
Labels: bug

#89 Fix: Edit invoice page shows success message even when backend update fails
  frontend/.prettierrc
  frontend/src/containers/Invoices/EditInvoiceContainer.tsx
Labels: bug

#87 fix send bug
  frontend/src/components/invoice/SendInvoiceModal.tsx
  frontend/src/containers/Invoices/ViewInvoicContainer.tsx
Labels: bug

#92 Feat documentation page
  frontend/src/components/landing/FAQ_Page/FAQBackground.tsx
  frontend/src/constants/Documentation/BusinessProcess.ts
  frontend/src/constants/Documentation/Integration.ts
  frontend/src/constants/Documentation/SideBar.tsx
  frontend/src/containers/Documentation/BusinessProcessContainer.tsx
  frontend/src/containers/Documentation/InvoiceCreationContainer.tsx
  frontend/src/containers/Documentation/OverviewContainer.tsx
  frontend/src/containers/Documentation/ReckonIntegrationContainer.tsx
  frontend/src/containers/Documentation/SMEGuidelinesContainer.tsx
  frontend/src/containers/Documentation/SendingContainer.tsx
  frontend/src/containers/Documentation/SideBarContainer.tsx
  frontend/src/containers/Documentation/UBLConversionContainer.tsx
  frontend/src/containers/Documentation/ValidationContainer.tsx
  frontend/src/containers/Landing/BenefitsContainer.tsx
  frontend/src/pages/DocumentationPage.tsx
  frontend/src/routes/index.tsx
Labels: enhancement

#93 Feat: update invoice status and email status badge rendering logic
  frontend/src/containers/Invoices/InvoiceTableContainer.tsx
Labels: enhancement

#101 Fix edit invoice
  backend/InvoiceBackend/Controllers/InvoicesController.cs
  frontend/src/components/invoice/InvoiceDetails.tsx
  frontend/src/components/invoice/InvoiceInformation.tsx
  frontend/src/components/invoice/InvoiceItems.tsx
  frontend/src/components/invoice/InvoiceTotal.tsx
  frontend/src/containers/Invoices/EditInvoiceContainer.tsx
Labels: bug

#102 feat: merge select page and book page
  frontend/src/containers/Books/BookContainer.tsx
  frontend/src/pages/BookPage.tsx
  frontend/src/pages/ReckonCallbackPage.tsx
  frontend/src/pages/SelectIntegrationPage.tsx
  frontend/src/routes/index.tsx
Labels: enhancement

#99 feat: add a simple validation functionality
  frontend/src/components/invoice/ValidationResultModal.tsx
  frontend/src/components/ui/dialog.tsx
  frontend/src/containers/Invoices/ViewInvoicContainer.tsx
  frontend/src/hooks/invoice/useValidateInvoicePeppol.ts
Labels: enhancement

#96 fix: rename Organization Name to Display Name
  frontend/src/containers/Customers/CreateCustomerContainer.tsx
  frontend/src/containers/Customers/EditCustomerContainer.tsx
  frontend/src/containers/Products/CreateProductContainer.tsx
  frontend/src/containers/Products/EditProductContainer.tsx
  frontend/src/types/product.ts
Labels: bug

#110 Updated overview, business process and integration sections of the do…
  frontend/src/constants/Documentation/BusinessProcess.ts
  frontend/src/constants/Documentation/Integration.ts
  frontend/src/containers/Documentation/OverviewContainer.tsx
Labels: enhancement

#123 fix: update invoice validation prompt
  frontend/src/hooks/invoice/useValidateInvoicePeppol.ts
Labels: bug

#122 update documentation page
  frontend/src/constants/Documentation/SideBar.tsx
  frontend/src/containers/Documentation/BackToTopButton.tsx
  frontend/src/containers/Documentation/InvoiceCreationContainer.tsx
  frontend/src/containers/Documentation/UBLConversionContainer.tsx
  frontend/src/containers/Documentation/ValidationContainer.tsx
  frontend/src/containers/Landing/ScrollToTopButton.tsx
  frontend/src/pages/DocumentationPage.tsx
Labels: enhancement

#133 Fix: fetch data delay bug
  frontend/src/App.tsx
  frontend/src/hooks/customer/useCreateCustomer.ts
  frontend/src/hooks/customer/useDeleteCustomer.ts
  frontend/src/hooks/customer/useEditCustomer.ts
  frontend/src/hooks/invoice/useCreateInvoice.ts
  frontend/src/hooks/invoice/useDeleteInvoice.ts
  frontend/src/hooks/invoice/useEditInvoice.ts
  frontend/src/hooks/invoice/useSendInvoice.ts
  frontend/src/hooks/product/useCreateProduct.ts
  frontend/src/hooks/product/useDeleteProduct.ts
  frontend/src/hooks/product/useEditProduct.ts
Labels: bug

#134 fix: update PDF crash bug
  frontend/src/hooks/invoice/useProcessInvoicePdf.ts
Labels: bug

#135 Feat: update landing page content
  frontend/src/components/common/Footer.tsx
  frontend/src/components/landing/FAQ_Page/FAQHelpSection.tsx
  frontend/src/components/landing/KeyFeatureHighlight.tsx
  frontend/src/constants/Landing/landingFAQ.tsx
  frontend/src/constants/Landing/landingFeature.ts
  frontend/src/constants/Landing/landingHero.ts
  frontend/src/constants/Landing/landingProcess.ts
  frontend/src/constants/Landing/landingbenefits.tsx
  frontend/src/pages/DocumentationPage.tsx
Labels: bug, enhancement

#95 Chore: add docker compose set-up
  .gitattributes
  .vscode/settings.json
  README.md
  backend/InvoiceBackend/.dockerignore
  backend/InvoiceBackend/DataAccess/AppDbContext.cs
  backend/InvoiceBackend/Dockerfile
  backend/InvoiceBackend/Infrastructure/DemoTokenSeeder.cs
  backend/InvoiceBackend/Program.cs
  backend/InvoiceBackend/appsettings.json
  backend/InvoiceBackend/entrypoint.sh
  docker-compose.yml
  frontend/.dockerignore
  frontend/Dockerfile
  frontend/nginx.conf
Labels: enhancement, chore

#139 chore: update docker demo token
  backend/InvoiceBackend/appsettings.json
Labels: chore

#140 fix: improve date handling and validation in invoice processing
  frontend/src/containers/Invoices/CreateInvoiceContainer.tsx
  frontend/src/hooks/invoice/usePreprocessInvoiceData.ts
  frontend/src/hooks/invoice/useProcessInvoicePdf.ts
Labels: bug
